name: travelapp
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  #颜色转换
  flutter_color_plugin: ^0.0.2
  #网络框架
  dio: ^3.0.9
  http: ^0.12.0+2
  rxdart: ^0.22.0
  #sp
  shared_preferences: ^0.5.2
  #权限
  permission_handler: ^3.1.0
  fish_redux: ^0.3.1
  #weview
  webview_flutter: ^0.3.14+1
  #富文本
  flutter_html: ^0.10.2
  #banner
  flutter_swiper: ^1.1.6
  event_bus: ^1.1.0
  #获取设备信息
  device_info: ^0.4.0+2
  #刷新widget
  flutter_easyrefresh: ^2.1.1
  #选择器
  flutter_picker: ^1.1.0
  #网络图片
  cached_network_image: ^2.0.0
  #适配
  flutter_screenutil: ^0.5.2
  #极光推送
  #  jpush_flutter: 0.0.13
  #网络请求动画
  flutter_spinkit: ^3.1.0
  #tuils
  common_utils: ^1.1.3
  #网络监听
  connectivity: ^0.4.3+2
  #序列化
  json_annotation: ^2.0.0
  #图片选择器
  image_picker: ^0.6.1
  video_player: ^0.10.5
  #图片缩放
  photo_view: ^0.4.2
  package_info: ^0.4.0+2
  #视频播放
  #  video_player: ^0.10.8+1
  wakelock: ^0.1.3+4
  open_iconic_flutter: ^0.3.0
  #微光
  shimmer: ^1.0.0
  #状态栏颜色
  flutter_statusbarcolor: any
  #  multi_image_picker: ^4.5.5
  flutter_custom_bottom_tab_bar:
    git: https://github.com/LiuC520/flutter_custom_bottom_tab_bar.git
  #吐司
  fluttertoast:
    path: plugins/FlutterToast
  #屏幕亮度调节
  screen: ^0.0.5
  flutter_datetime_picker: 1.3.8
  flutter_cupertino_date_picker: ^1.0.12
  #  city_pickers: ^0.1.30
  lpinyin: ^1.0.7
  #  #定位
  #  location: ^2.3.5
  #  google_maps_flutter: ^0.5.22+33
  qr_flutter: ^3.2.0
  path_provider: ^1.6.5
  image_gallery_saver: ^1.2.2
  #  left_scroll_actions: ^1.5.3
  #微信分享
  fluwx_no_pay: ^2.4.0+1
  marquee_flutter: ^0.1.2
  charts_flutter: ^0.9.0
  flutter_switch_plus: ^0.0.1
  md2_tab_indicator: ^1.0.2
  audioplayers: ^0.13.1
  vibrate: ^0.0.4
  #  flutter_alipay: "^1.0.0"
  #  fluwx: ^2.5.0+1
  #国际化
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.0
  intl_translation: ^0.17.2
  #数据同步，多线程
  synchronized: ^2.2.0
  url_launcher: ^5.2.7
  date_format: ^1.0.8
  sign_in_apple: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
